# Generated by Django 6.0 on 2026-01-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0003_rename_favorite_activity_entryv1_biggest_idol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryv1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
