# Generated by Django 6.0 on 2026-01-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0004_entryv1_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryv1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
