# Generated by Django 6.0 on 2026-01-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0005_alter_entryv1_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default='wEhBBN0l', max_length=100)),
            ],
        ),
    ]
