# Generated by Django 6.0 on 2026-01-06 13:27

import Entries.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0006_createcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcode',
            name='secret',
            field=models.CharField(default=Entries.helpers.generate_secret, max_length=100),
        ),
    ]
