# Generated by Django 6.0 on 2026-01-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0007_alter_createcode_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcode',
            name='purpose',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
