# Generated by Django 6.0 on 2026-01-07 08:41

import Entries.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0008_createcode_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='createcode',
            name='secret',
            field=models.CharField(default=Entries.helpers.generate_secret, max_length=100, primary_key=True, serialize=False),
        ),
    ]
